const state={step:0,selected:null,weight:812};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
const stage=document.getElementById("stage"),progress=document.getElementById("progress"),next=document.getElementById("nextBtn"),back=document.getElementById("backBtn");
const stepKeys=["demo.declare","demo.qualify","demo.match","demo.collect","demo.weigh","demo.receive","demo.value","demo.certify"];
function renderProgress(){progress.innerHTML=stepKeys.map((k,i)=>`<div class="pstep ${i<=state.step?"done":""}" title="${esc(t(k))}"></div>`).join("")}
function render(){
 renderProgress(); back.disabled=state.step===0; back.style.opacity=state.step===0?".4":"1";
 const p=demoData.producers[0], v=state.selected?demoData.recyclers.find(x=>x.id===state.selected):demoData.recyclers[0], c=demoData.collectors[0];
 const heads=[
  ["01 · "+t("demo.declare"),t("demo.h1"),t("demo.p1")],["02 · "+t("demo.qualify"),t("demo.h2"),t("demo.p2")],
  ["03 · "+t("demo.match"),t("demo.h3"),t("demo.p3")],["04 · "+t("demo.collect"),t("demo.h4"),t("demo.p4")],
  ["05 · "+t("demo.weigh"),t("demo.h5"),t("demo.p5")],["06 · "+t("demo.receive"),t("demo.h6"),t("demo.p6")],
  ["07 · "+t("demo.value"),t("demo.h7"),t("demo.p7")],["08 · "+t("demo.certify"),t("demo.h8"),t("demo.p8")]
 ];
 let body="";
 if(state.step===0) body=`<div class="form-grid"><div class="field"><label>${t("demo.producer")}</label><strong>${p.name}</strong></div><div class="field"><label>${t("demo.location")}</label><strong>${p.city}</strong></div><div class="field"><label>${t("demo.material")}</label><strong>${p.material}</strong></div><div class="field"><label>${t("demo.quantity")}</label><strong>${p.weight} kg</strong></div><div class="field"><label>${t("demo.quality")}</label><strong>${p.quality}</strong></div><div class="field"><label>${t("demo.availability")}</label><strong>${p.frequency}</strong></div></div>`;
 if(state.step===1) body=`<div class="check-list">${[t("demo.material")+" : Carton / Papier","850 kg","Yaoundé","Triée","EL-2026-0001"].map((x,i)=>`<div class="check"><b>✓</b>${[t("demo.material")+" : Carton / Papier",t("demo.quantity")+" : 850 kg",t("demo.location")+" : Yaoundé",t("demo.quality")+" : Triée","Offre créée : EL-2026-0001"][i]}</div>`).join("")}</div><div class="field" style="margin-top:20px"><label>${t("demo.classification")}</label><strong>${t("demo.confidence")}</strong><p>${t("demo.ai")}</p></div>`;
 if(state.step===2) body=`<div class="score-grid">${demoData.recyclers.map(x=>`<article class="match-card ${state.selected===x.id?"selected":""}" data-id="${x.id}"><div class="score">${x.score}%</div><div class="meter"><i style="width:${x.score}%"></i></div><h3>${x.name}</h3><p>${x.material}<br>${t("demo.need")} : ${x.need}<br>${t("demo.distance")} : ${x.distance}</p><small>${t("demo.matchcompat")}</small></article>`).join("")}</div>`;
 if(state.step===3) body=`<div class="route"><div class="place">Imprimerie<br><small>Yaoundé</small></div><div class="place">${c.name}<br><small>${c.distance}</small></div><div class="place">${v.name}<br><small>${t("actor.v")}</small></div></div><div class="check-list"><div class="check"><b>✓</b>${t("demo.collector")} : ${c.name}</div><div class="check"><b>✓</b>${t("demo.estimated")} : 850 kg</div><div class="check"><b>✓</b>${t("demo.destination")} : ${v.name}</div></div>`;
 if(state.step===4) body=`<div class="weight"><label>${t("demo.realweight")}</label><strong>${state.weight} kg</strong><p>${t("demo.initial")} : 850 kg · ${t("demo.gap")} : ${state.weight-850} kg</p><input id="weightInput" type="number" value="${state.weight}" min="1"><p>${t("demo.edit")}</p></div>`;
 if(state.step===5) body=`<div class="success"><div class="success-icon">✓</div><h3>${t("demo.received")}</h3><p>${v.name} ${t("demo.receivedp")} ${state.weight} kg ${p.material}.</p></div><div class="trace-card"><div class="trace-row"><span class="dot"></span><strong>${t("demo.origin")}</strong><span>Yaoundé · ${p.name}</span></div><div class="trace-row"><span class="dot"></span><strong>${t("demo.weight")}</strong><span>${state.weight} kg</span></div><div class="trace-row"><span class="dot"></span><strong>${t("demo.quality")}</strong><span>${t("demo.accepted")}</span></div></div>`;
 if(state.step===6) body=`<div class="success"><div class="success-icon">↻</div><h3>${t("demo.valued")}</h3><p>${t("demo.valuedp")}</p></div><div class="final-stats"><div><strong>${state.weight} kg</strong><span>${t("demo.receivedkg")}</span></div><div><strong>5/5</strong><span>${t("demo.traced")}</span></div><div><strong>Yaoundé</strong><span>${t("demo.zone")}</span></div><div><strong>Actif</strong><span>${t("demo.active")}</span></div></div>`;
 if(state.step===7) body=`<div class="certificate"><div class="cert-head"><div><div class="eyebrow">ECO-LOOP</div><h3>${t("demo.certificate")}</h3><strong>LOT #EL-2026-0001</strong></div><div class="qr"></div></div><div class="form-grid"><div class="field"><label>${t("demo.material")}</label><strong>${p.material}</strong></div><div class="field"><label>${t("demo.weight")}</label><strong>${state.weight} kg</strong></div><div class="field"><label>${t("demo.origin")}</label><strong>Yaoundé</strong></div><div class="field"><label>${t("actor.v")}</label><strong>${v.name}</strong></div></div><div class="trace-card" style="margin-top:20px">${["demo.declared","demo.qualified","demo.collected","demo.weighed","demo.receptioned","demo.valorized"].map(k=>`<div class="trace-row"><span class="dot"></span><strong>${t(k)}</strong><span>✓</span></div>`).join("")}</div><p><strong>${t("demo.simulated")}</strong> ${t("demo.blockchain")}</p></div>`;
 const h=heads[state.step]; stage.innerHTML=`<div class="stage-head"><div><div class="stage-kicker">${h[0]}</div><h2>${h[1]}</h2><p>${h[2]}</p></div></div>${body}`;
 next.innerHTML=state.step===7?`<span>${t("demo.restart")}</span>`:`<span>${t("demo.next")}</span>`;
 if(state.step===2)document.querySelectorAll(".match-card").forEach(card=>card.onclick=()=>{state.selected=card.dataset.id;render()});
 if(state.step===4)document.getElementById("weightInput").oninput=e=>{state.weight=Number(e.target.value)||0;render()};
}
next.onclick=()=>{if(state.step===7){state.step=0;state.selected=null;state.weight=812}else if(state.step===2&&!state.selected){state.selected=demoData.recyclers[0].id;state.step++}else state.step++;render();window.scrollTo({top:0,behavior:"smooth"})};
back.onclick=()=>{if(state.step>0){state.step--;render()}};
document.addEventListener("languagechange",render);
render();