const I18N = {
fr:{
"nav.solution":"Solution","nav.process":"Comment ça marche","nav.materials":"Matières","nav.vision":"Vision","nav.demo":"Explorer la démo","nav.site":"← Site","nav.lang":"English",
"hero.eyebrow":"Économie circulaire · Yaoundé · Cameroun","hero.title":"Donner une <em>seconde vie</em> aux matières.","hero.lead":"ECO-LOOP connecte ceux qui produisent des matières résiduelles avec ceux qui peuvent les réutiliser, les transformer ou les recycler.","hero.demo":"Explorer ECO-LOOP →","hero.process":"Voir comment ça marche ↓",
"problem.eyebrow":"Le problème","problem.title":"Et si un déchet n'était pas vraiment un déchet ?","problem.lead":"Des matières encore utiles existent déjà. Le défi est de les faire circuler au bon endroit, au bon moment et à un coût viable.",
"problem.c1":"Des matières perdues","problem.p1":"Cartons, plastiques, bois, verre et autres matières peuvent encore avoir une valeur.","problem.c2":"Une offre dispersée","problem.p2":"Celui qui possède une matière ne connaît pas forcément celui qui la recherche.","problem.c3":"Une logistique complexe","problem.p3":"Collecte, transport et regroupement peuvent rendre une opération non rentable.","problem.c4":"Peu de visibilité","problem.p4":"Après la collecte, il est souvent difficile de suivre le parcours de la matière.",
"solution.eyebrow":"La solution","solution.title":"ECO-LOOP transforme les flux de déchets en chaînes de valeur.","solution.lead":"Une infrastructure qui relie les acteurs, qualifie les matières et organise leur parcours jusqu'à leur prochaine utilisation.",
"actor.p":"Producteur","actor.pd":"Déclare une matière disponible : type, quantité, qualité, localisation et disponibilité.","actor.ps":"→ Déclarer",
"actor.v":"Valorisateur","actor.vd":"Indique les matières recherchées et les caractéristiques dont il a besoin.","actor.vs":"→ Rechercher",
"actor.c":"Collecteur","actor.cd":"Assure collecte, transport, regroupement et pesée.","actor.cs":"→ Acheminer",
"actor.e":"ECO-LOOP","actor.ed":"Coordonne qualification, matching, logistique, transactions, traçabilité et données.","actor.es":"→ Orchestrer",
"process.eyebrow":"Le parcours","process.title":"Une matière. Un parcours. Une nouvelle vie.",
"step.1":"Déclarer","step.1d":"Le producteur renseigne sa matière et sa disponibilité.","step.2":"Qualifier","step.2d":"La matière est décrite, contrôlée et progressivement qualifiée par les données.","step.3":"Matcher","step.3d":"ECO-LOOP rapproche offre et demande selon matière, volume, qualité, distance et disponibilité.","step.4":"Collecter","step.4d":"Un collecteur organise le déplacement de la matière.","step.5":"Peser & tracer","step.5d":"Le poids réel et les événements du lot sont enregistrés.","step.6":"Valoriser","step.6d":"Le valorisateur donne une seconde vie à la matière.",
"materials.eyebrow":"Les matières","materials.title":"Une matière. Plusieurs vies.","materials.lead":"Les filières seront intégrées progressivement, selon les volumes, la demande et la viabilité logistique.",
"ai.eyebrow":"Intelligence","ai.title":"L'IA au service de la circularité.","ai.lead":"ECO-LOOP commence avec des règles métier et des données réelles. L'intelligence s'enrichit ensuite avec les transactions.",
"ai.1":"Matching","ai.1d":"Identifier les correspondances pertinentes entre offres et besoins.","ai.2":"Qualification","ai.2d":"Assister l'identification d'une matière, notamment à partir d'une photo.","ai.3":"Prévision","ai.3d":"Anticiper les volumes disponibles et les besoins récurrents.","ai.4":"Anomalies","ai.4d":"Repérer les variations inhabituelles de poids, volume ou activité.",
"trace.eyebrow":"Traçabilité","trace.title":"De la matière à sa seconde vie.","trace.lead":"Chaque lot peut progressivement construire un historique vérifiable.","trace.note":"La blockchain est une évolution possible pour renforcer la vérifiabilité de certains certificats ; elle n'est pas nécessaire au fonctionnement initial.",
"impact.eyebrow":"Impact","impact.title":"Mesurer ce qui circule et ce qui retrouve une valeur.","impact.kg":"kg · démonstration","impact.mat":"matières · cible","impact.act":"acteurs · modèle","impact.city":"ville · départ",
"vision.eyebrow":"Notre vision","vision.title":"Commencer à Yaoundé.<br>Construire pour le Cameroun.","vision.p":"ECO-LOOP commence volontairement à petite échelle : quelques matières, quelques producteurs, valorisateurs et collecteurs. Le modèle s'étend à mesure que les chaînes de valorisation sont validées.",
"cta.eyebrow":"ECO-LOOP","cta.title":"Et si votre déchet devenait la matière première de quelqu'un d'autre ?","cta.button":"Découvrir la démonstration →","footer":"Prototype conceptuel · Yaoundé, Cameroun","contact.whatsapp":"Contacter Mbôra sur WhatsApp",
"demo.badge":"Prototype interactif","demo.eyebrow":"Démonstration · données simulées","demo.title":"Suivez une matière jusqu'à sa seconde vie.","demo.lead":"Un scénario fictif à Yaoundé : une imprimerie déclare 850 kg de carton/papier. ECO-LOOP organise ensuite qualification, matching, collecte, pesée, réception et valorisation.","demo.back":"← Site","demo.backbtn":"← Retour","demo.start":"Commencer →","demo.next":"Continuer →","demo.restart":"Rejouer la démonstration →",
"demo.declare":"Déclarer","demo.qualify":"Qualifier","demo.match":"Matcher","demo.collect":"Collecter","demo.weigh":"Peser","demo.receive":"Réceptionner","demo.value":"Valoriser","demo.certify":"Certifier",
"demo.h1":"Une matière disponible entre dans ECO-LOOP.","demo.p1":"Créer une offre de matière.","demo.h2":"La déclaration devient un lot exploitable.","demo.p2":"Qualification simulée.","demo.h3":"ECO-LOOP recherche des correspondances.","demo.p3":"Sélectionner une correspondance.","demo.h4":"Le lot est confié à un collecteur.","demo.p4":"Simuler la collecte.","demo.h5":"La quantité réelle remplace l'estimation.","demo.p5":"Enregistrer la pesée.","demo.h6":"Le valorisateur confirme la réception.","demo.p6":"Confirmer la réception.","demo.h7":"Le lot reçoit une nouvelle destination.","demo.p7":"Marquer comme valorisé.","demo.h8":"Le parcours devient une preuve lisible.","demo.p8":"Voir le certificat.",
"demo.producer":"Producteur","demo.location":"Localisation","demo.material":"Type de matière","demo.quantity":"Quantité estimée","demo.quality":"Qualité","demo.availability":"Disponibilité","demo.classification":"Classification","demo.confidence":"Carton / Papier · confiance simulée 94 %","demo.ai":"Cette classification est une démonstration. Une future IA pourra assister la qualification à partir des données et images.",
"demo.matchcompat":"Compatibilité matière · volume · qualité · distance · disponibilité","demo.need":"Besoin","demo.distance":"Distance","demo.collector":"Collecteur assigné","demo.destination":"Destination","demo.estimated":"Quantité estimée","demo.realweight":"POIDS RÉEL","demo.initial":"Estimation initiale","demo.gap":"Écart","demo.edit":"Modifiez la valeur pour simuler la pesée.","demo.received":"Réception confirmée","demo.receivedp":"a reçu le lot de","demo.origin":"Origine","demo.weight":"Poids","demo.accepted":"Acceptée","demo.valued":"Lot valorisé","demo.valuedp":"La matière quitte le statut de simple déchet pour entrer dans une nouvelle chaîne de valeur.","demo.receivedkg":"réceptionnés","demo.traced":"étapes tracées","demo.zone":"zone pilote","demo.active":"lot","demo.certificate":"Certificat de traçabilité","demo.declared":"Déclaré","demo.qualified":"Qualifié","demo.collected":"Collecté","demo.weighed":"Pesé","demo.receptioned":"Réceptionné","demo.valorized":"Valorisé","demo.simulated":"Prototype — certificat simulé.","demo.blockchain":"La blockchain pourra éventuellement ancrer l'empreinte d'un certificat dans une phase ultérieure."
},
en:{
"nav.solution":"Solution","nav.process":"How it works","nav.materials":"Materials","nav.vision":"Vision","nav.demo":"Explore demo","nav.site":"← Site","nav.lang":"Français",
"hero.eyebrow":"Circular economy · Yaoundé · Cameroon","hero.title":"Give materials a <em>second life</em>.","hero.lead":"ECO-LOOP connects those who generate residual materials with those who can reuse, transform or recycle them.","hero.demo":"Explore ECO-LOOP →","hero.process":"See how it works ↓",
"problem.eyebrow":"The problem","problem.title":"What if waste wasn't really waste?","problem.lead":"Useful materials already exist. The challenge is moving them to the right place, at the right time and at a viable cost.",
"problem.c1":"Lost materials","problem.p1":"Cardboard, plastics, wood, glass and other materials can still have value.","problem.c2":"A fragmented supply","problem.p2":"The person holding a material does not necessarily know who is looking for it.","problem.c3":"Complex logistics","problem.p3":"Collection, transport and aggregation can make an operation unprofitable.","problem.c4":"Limited visibility","problem.p4":"After collection, it is often difficult to track the material's journey.",
"solution.eyebrow":"The solution","solution.title":"ECO-LOOP turns waste flows into value chains.","solution.lead":"An infrastructure that connects stakeholders, qualifies materials and organizes their journey to their next use.",
"actor.p":"Producer","actor.pd":"Declares an available material: type, quantity, quality, location and availability.","actor.ps":"→ Declare",
"actor.v":"Recycler","actor.vd":"Indicates the materials and characteristics it needs.","actor.vs":"→ Search",
"actor.c":"Collector","actor.cd":"Handles collection, transport, aggregation and weighing.","actor.cs":"→ Move",
"actor.e":"ECO-LOOP","actor.ed":"Coordinates qualification, matching, logistics, transactions, traceability and data.","actor.es":"→ Orchestrate",
"process.eyebrow":"The journey","process.title":"One material. One journey. A new life.",
"step.1":"Declare","step.1d":"The producer enters the material and its availability.","step.2":"Qualify","step.2d":"The material is described, checked and progressively qualified through data.","step.3":"Match","step.3d":"ECO-LOOP matches supply and demand by material, volume, quality, distance and availability.","step.4":"Collect","step.4d":"A collector organizes the material's movement.","step.5":"Weigh & track","step.5d":"The actual weight and lot events are recorded.","step.6":"Valorize","step.6d":"The recycler gives the material a second life.",
"materials.eyebrow":"Materials","materials.title":"One material. Many lives.","materials.lead":"Material streams will be integrated progressively according to volumes, demand and logistical viability.",
"ai.eyebrow":"Intelligence","ai.title":"AI in service of circularity.","ai.lead":"ECO-LOOP starts with business rules and real data. Intelligence can then improve through transactions.",
"ai.1":"Matching","ai.1d":"Identify relevant matches between available materials and needs.","ai.2":"Qualification","ai.2d":"Assist material identification, including from a photo.","ai.3":"Forecasting","ai.3d":"Anticipate available volumes and recurring needs.","ai.4":"Anomalies","ai.4d":"Detect unusual changes in weight, volume or activity.",
"trace.eyebrow":"Traceability","trace.title":"From material to its second life.","trace.lead":"Each lot can progressively build a verifiable history.","trace.note":"Blockchain may later strengthen the verifiability of certain certificates; it is not required for the initial operation.",
"impact.eyebrow":"Impact","impact.title":"Measure what circulates and what regains value.","impact.kg":"kg · demonstration","impact.mat":"materials · target","impact.act":"actors · model","impact.city":"city · starting point",
"vision.eyebrow":"Our vision","vision.title":"Start in Yaoundé.<br>Build for Cameroon.","vision.p":"ECO-LOOP deliberately starts small: a few materials, producers, recyclers and collectors. The model expands as value chains are validated.",
"cta.eyebrow":"ECO-LOOP","cta.title":"What if your waste became someone else's raw material?","cta.button":"Discover the demo →","footer":"Concept prototype · Yaoundé, Cameroon","contact.whatsapp":"Contact Mbôra on WhatsApp",
"demo.badge":"Interactive prototype","demo.eyebrow":"Demo · simulated data","demo.title":"Follow a material to its second life.","demo.lead":"A fictional scenario in Yaoundé: a printing company declares 850 kg of cardboard/paper. ECO-LOOP then organizes qualification, matching, collection, weighing, receiving and valorization.","demo.back":"← Site","demo.backbtn":"← Back","demo.start":"Start →","demo.next":"Continue →","demo.restart":"Replay demonstration →",
"demo.declare":"Declare","demo.qualify":"Qualify","demo.match":"Match","demo.collect":"Collect","demo.weigh":"Weigh","demo.receive":"Receive","demo.value":"Valorize","demo.certify":"Certify",
"demo.h1":"Available material enters ECO-LOOP.","demo.p1":"Create a material offer.","demo.h2":"The declaration becomes a usable lot.","demo.p2":"Simulated qualification.","demo.h3":"ECO-LOOP searches for matches.","demo.p3":"Select a match.","demo.h4":"The lot is assigned to a collector.","demo.p4":"Simulate collection.","demo.h5":"Actual quantity replaces the estimate.","demo.p5":"Record the weighing.","demo.h6":"The recycler confirms receipt.","demo.p6":"Confirm receipt.","demo.h7":"The lot receives a new destination.","demo.p7":"Mark as valorized.","demo.h8":"The journey becomes readable proof.","demo.p8":"View certificate.",
"demo.producer":"Producer","demo.location":"Location","demo.material":"Material type","demo.quantity":"Estimated quantity","demo.quality":"Quality","demo.availability":"Availability","demo.classification":"Classification","demo.confidence":"Cardboard / Paper · simulated confidence 94%","demo.ai":"This classification is a demonstration. Future AI could assist qualification using data and images.",
"demo.matchcompat":"Material · volume · quality · distance · availability compatibility","demo.need":"Need","demo.distance":"Distance","demo.collector":"Assigned collector","demo.destination":"Destination","demo.estimated":"Estimated quantity","demo.realweight":"ACTUAL WEIGHT","demo.initial":"Initial estimate","demo.gap":"Difference","demo.edit":"Change the value to simulate weighing.","demo.received":"Receipt confirmed","demo.receivedp":"received the","demo.origin":"Origin","demo.weight":"Weight","demo.accepted":"Accepted","demo.valued":"Lot valorized","demo.valuedp":"The material moves from waste status into a new value chain.","demo.receivedkg":"received","demo.traced":"steps tracked","demo.zone":"pilot area","demo.active":"lot","demo.certificate":"Traceability certificate","demo.declared":"Declared","demo.qualified":"Qualified","demo.collected":"Collected","demo.weighed":"Weighed","demo.receptioned":"Received","demo.valorized":"Valorized","demo.simulated":"Prototype — simulated certificate.","demo.blockchain":"Blockchain may eventually anchor a certificate fingerprint in a later phase."
}};
function getLang(){return localStorage.getItem("ecoLoopLang")||"fr"}
function t(k){return (I18N[getLang()]&&I18N[getLang()][k])||I18N.fr[k]||k}
function setLang(lang){localStorage.setItem("ecoLoopLang",lang);document.documentElement.lang=lang;document.dispatchEvent(new CustomEvent("languagechange",{detail:lang}));applyI18n()}
function applyI18n(){
 document.querySelectorAll("[data-i18n]").forEach(el=>el.innerHTML=t(el.dataset.i18n));
 document.querySelectorAll("[data-i18n-text]").forEach(el=>el.textContent=t(el.dataset.i18nText));
 const btn=document.getElementById("langToggle"); if(btn) btn.textContent=t("nav.lang");
 document.querySelectorAll(".lang-option").forEach(x=>x.classList.toggle("active",x.dataset.lang===getLang()));
}
document.addEventListener("DOMContentLoaded",()=>{document.documentElement.lang=getLang();applyI18n();const b=document.getElementById("langToggle");if(b)b.onclick=()=>setLang(getLang()==="fr"?"en":"fr")});
