const I18N={fr:{
'nav.problem':'Le problème','nav.loop':'La boucle','nav.proof':'Ce que l’on suit','nav.demo':'Voir la démo',
'hero.eyebrow':'ECO-LOOP · Mbôra','hero.title':'Et si ce qui ne sert plus pouvait encore servir ailleurs ?','hero.lead':'ECO-LOOP aide à identifier les ressources disponibles, comprendre leur valeur et les connecter à un nouvel usage avant qu’elles ne deviennent une perte.','hero.cta':'Explorer une boucle →','hero.link':'Comprendre le problème ↓','hero.orb':'VALEUR EN CIRCULATION',
'hero.resourceTag':'RESSOURCE','hero.resource':'80 chaises','hero.resourceMeta':'Bon état · Yaoundé','hero.needTag':'BESOIN','hero.need':'Équipement','hero.needMeta':'École · Yaoundé',
'waste.eyebrow':'Déchets · une autre étape de la boucle','waste.title':'Et quand la ressource devient un déchet, la boucle ne s’arrête pas.','waste.lead':'ECO-LOOP aide aussi à rendre visibles les déchets, qualifier leur nature et leur potentiel, puis les orienter vers la collecte, le tri, la récupération, la transformation ou le recyclage.','waste.c1':'Prévenir','waste.p1':'Identifier une possibilité de réemploi ou de réparation avant que l’objet ne devienne un déchet.','waste.c2':'Qualifier','waste.p2':'Décrire la matière, la quantité, l’état, le lieu et les contraintes de prise en charge.','waste.c3':'Valoriser','waste.p3':'Relier le déchet à un acteur capable de le collecter, trier, récupérer, transformer ou recycler.',
'cases.tag.entreprise':'ENTREPRISE','cases.tag.chantier':'CHANTIER','cases.tag.industrie':'INDUSTRIE','cases.tag.individu':'INDIVIDU',
'ai.r1':'Ressource','ai.r1b':'Besoin','ai.r2':'État','ai.r2b':'Trajectoire','ai.r3':'Résultat','ai.r3b':'Nouvelle connaissance',
'vision.city1':'YAOUNDÉ','vision.city2':'CAMEROUN','vision.city3':'AFRIQUE','contact.aria':'WhatsApp Mbôra',

'problem.eyebrow':'Le problème réel','problem.title':'Une ressource peut perdre sa valeur avant de devenir un déchet.','problem.lead':'Le problème n’est pas toujours l’absence de ressources. Elles peuvent être dispersées, invisibles, mal décrites, difficiles à transférer ou déconnectées d’un besoin.','problem.c1':'On ne sait pas ce qui existe','problem.p1':'Une entreprise, un chantier ou une organisation possède parfois des équipements, matériaux ou surplus dont personne d’autre ne connaît l’existence.','problem.c2':'On ne sait pas quoi en faire','problem.p2':'Vendre, réparer, partager, donner, transformer ou réutiliser : la bonne trajectoire dépend de l’état, du besoin et du contexte.','problem.c3':'Le transfert peut échouer','problem.p3':'Qualité, confiance, distance, stockage et transport peuvent empêcher une ressource encore utile de rejoindre son prochain usage.',
'observe.eyebrow':'Observer avant d’agir','observe.title':'ECO-LOOP commence par comprendre la ressource.','observe.lead':'Comme SIGNAL transforme un signal en information exploitable, ECO-LOOP transforme une ressource déclarée en information utile à la décision.','observe.r1':'Ce qui existe','observe.r1v':'80 chaises','observe.r2':'État','observe.r2v':'Bon état','observe.r3':'Lieu','observe.r3v':'Yaoundé','observe.r4':'Possibilités','observe.r4v':'Réemploi · réparation · transfert',
'loop.title':'Identifier → comprendre → relier → agir → suivre.','loop.lead':'La plateforme ne se limite pas à publier une annonce. Elle construit une boucle de valeur autour de la ressource.','loop.s1':'Identifier','loop.p1':'Déclarer une ressource disponible.','loop.s2':'Qualifier','loop.p2':'Décrire son état, sa quantité, son lieu et ses contraintes.','loop.s3':'Relier','loop.p3':'Trouver un besoin, un acteur ou une trajectoire pertinente.','loop.s4':'Agir','loop.p4':'Réparer, transférer, partager, transformer ou réutiliser.','loop.s5':'Suivre','loop.p5':'Enregistrer ce qui s’est réellement passé et la valeur récupérée.',
'proof.eyebrow':'La valeur après la déclaration','proof.title':'Une ressource devient une histoire vérifiable.','proof.lead':'ECO-LOOP garde le fil : origine, état, correspondance, action et résultat. L’objectif est de construire de la confiance sans prétendre garantir une vérité absolue.','proof.t1':'Ressource déclarée','proof.t2':'Contexte qualifié','proof.t3':'Besoin identifié','proof.t4':'Action réalisée','proof.t5':'Résultat suivi',
'cases.eyebrow':'Même logique, plusieurs situations','cases.title':'Pas seulement des déchets. Des ressources, des besoins et des possibilités.','cases.c1':'Un bureau ferme','cases.p1':'Mobilier et équipements sont identifiés, qualifiés puis proposés à des acteurs qui peuvent les réutiliser.','cases.c2':'Un chantier termine','cases.p2':'Des matériaux encore utilisables sont repérés avant leur stockage ou leur élimination.','cases.c3':'Un flux devient disponible','cases.p3':'Un sous-produit ou stock dormant peut être relié à un autre usage productif.','cases.c4':'Un équipement ne sert plus','cases.p4':'ECO-LOOP cherche d’abord une nouvelle utilisation, une réparation ou un transfert.',
'ai.eyebrow':'Intelligence','ai.title':'Plus il y a de boucles, plus le système apprend.','ai.lead':'Le matching peut commencer avec des règles simples. Les données issues des boucles réelles peuvent ensuite améliorer les correspondances et les recommandations.',
'vision.eyebrow':'Vision Mbôra','vision.title':'Faire circuler la valeur avant qu’elle ne soit perdue.','vision.p':'Commencer avec des cas simples et mesurables à Yaoundé, apprendre des usages réels, puis étendre progressivement les boucles et les acteurs.','cta.title':'Avant de jeter, remplacer ou acheter : regardons ce qui existe déjà.','cta.demo':'Explorer la démo','cta.contact':'Parler à Mbôra sur WhatsApp','footer':'Prototype conceptuel · Yaoundé, Cameroun',
'demo.badge':'Prototype interactif','demo.back':'← Site','demo.eyebrow':'Une ressource · un contexte · une boucle','demo.title':'Que peut-on encore faire avec cette ressource ?','demo.lead':'Suivez un scénario fictif : une entreprise libère 80 chaises en bon état à Yaoundé. ECO-LOOP observe, qualifie, relie, déclenche une action puis suit le résultat.','demo.backbtn':'← Retour','demo.start':'Commencer →','demo.next':'Continuer →','demo.restart':'Rejouer la boucle','demo.observe':'Observer','demo.context':'Qualifier','demo.match':'Relier','demo.action':'Agir','demo.follow':'Suivre','demo.h1':'Une ressource apparaît. ECO-LOOP commence par l’observer.','demo.h2':'Le contexte transforme une annonce en information utile.','demo.h3':'Un besoin compatible apparaît. La boucle peut commencer.','demo.h4':'Une action concrète remet la ressource en circulation.','demo.h5':'Le résultat est suivi pour savoir ce qui a réellement changé.','demo.dataResource':'80 chaises','demo.dataState':'Bon état','demo.dataCity':'Yaoundé','demo.dataNeed':'Équipement pour une école','demo.dataActor':'École Les Cocotiers','demo.dataAction':'Transfert vers l’école','demo.dataResult':'80 chaises remises en usage','demo.matchScore':'92%','demo.signal':'RESSOURCE SIGNALÉE','demo.obsText':'80 chaises sont disponibles après la fermeture d’un bureau. Elles sont encore utilisables.','demo.available':'Disponible','demo.resource':'Ressource','demo.state':'État','demo.location':'Localisation','demo.possibilities':'Possibilités','demo.possibilitiesV':'Réemploi · réparation · transfert','demo.qualification':'Qualification','demo.qualificationV':'Informations suffisantes pour rechercher une trajectoire pertinente.','demo.need':'Besoin','demo.matchReason':'Même zone géographique · quantité compatible · état adapté.','demo.compatible':'Correspondance plausible','demo.actionTag':'ACTION CONFIRMÉE','demo.actionText':'Les chaises sont transférées vers l’école plutôt que stockées ou éliminées.','demo.confirmed':'Trajet confirmé','demo.followTag':'RÉSULTAT SUIVI','demo.resultText':'La ressource a trouvé un nouvel usage. La boucle laisse une trace de ce qui s’est réellement passé.','demo.units':'unités','demo.newUse':'nouvel usage','demo.tracked':'suivi','contact.whatsapp':'Contacter Mbôra sur WhatsApp · +237 680 485 422'
},en:{
'nav.problem':'The problem','nav.loop':'The loop','nav.proof':'What we track','nav.demo':'See the demo',
'hero.eyebrow':'ECO-LOOP · Mbôra','hero.title':'What if something no longer useful here could still be useful somewhere else?','hero.lead':'ECO-LOOP helps identify available resources, understand their value and connect them to a new use before they become a loss.','hero.cta':'Explore a loop →','hero.link':'Understand the problem ↓','hero.orb':'VALUE IN CIRCULATION',
'hero.resourceTag':'RESOURCE','hero.resource':'80 chairs','hero.resourceMeta':'Good condition · Yaoundé','hero.needTag':'NEED','hero.need':'Equipment','hero.needMeta':'School · Yaoundé',
'waste.eyebrow':'Waste · another stage of the loop','waste.title':'And when a resource becomes waste, the loop does not stop.','waste.lead':'ECO-LOOP also helps make waste visible, qualify its nature and potential, then direct it toward collection, sorting, recovery, transformation or recycling.','waste.c1':'Prevent','waste.p1':'Identify reuse or repair before an item becomes waste.','waste.c2':'Qualify','waste.p2':'Describe the material, quantity, condition, location and handling constraints.','waste.c3':'Recover value','waste.p3':'Connect waste with an actor able to collect, sort, recover, transform or recycle it.',
'cases.tag.entreprise':'BUSINESS','cases.tag.chantier':'CONSTRUCTION','cases.tag.industrie':'INDUSTRY','cases.tag.individu':'INDIVIDUAL',
'ai.r1':'Resource','ai.r1b':'Need','ai.r2':'Condition','ai.r2b':'Path','ai.r3':'Result','ai.r3b':'New knowledge',
'vision.city1':'YAOUNDÉ','vision.city2':'CAMEROON','vision.city3':'AFRICA','contact.aria':'Mbôra WhatsApp',

'problem.eyebrow':'The real problem','problem.title':'A resource can lose its value before it becomes waste.','problem.lead':'The problem is not always a lack of resources. They can be scattered, invisible, poorly described, difficult to transfer or disconnected from a need.','problem.c1':'We do not know what exists','problem.p1':'A company, construction site or organisation may hold equipment, materials or surplus that nobody else knows about.','problem.c2':'We do not know what to do with it','problem.p2':'Sell, repair, share, donate, transform or reuse: the right path depends on condition, need and context.','problem.c3':'Transfer can fail','problem.p3':'Quality, trust, distance, storage and transport can prevent a still-useful resource from reaching its next use.',
'observe.eyebrow':'Observe before acting','observe.title':'ECO-LOOP starts by understanding the resource.','observe.lead':'Just as SIGNAL turns a signal into usable information, ECO-LOOP turns a declared resource into information that supports a decision.','observe.r1':'What exists','observe.r1v':'80 chairs','observe.r2':'Condition','observe.r2v':'Good condition','observe.r3':'Location','observe.r3v':'Yaoundé','observe.r4':'Possibilities','observe.r4v':'Reuse · repair · transfer',
'loop.title':'Identify → understand → connect → act → follow.','loop.lead':'The platform is not just a place to publish an ad. It builds a value loop around the resource.','loop.s1':'Identify','loop.p1':'Declare an available resource.','loop.s2':'Qualify','loop.p2':'Describe its condition, quantity, location and constraints.','loop.s3':'Connect','loop.p3':'Find a need, actor or relevant path.','loop.s4':'Act','loop.p4':'Repair, transfer, share, transform or reuse.','loop.s5':'Follow','loop.p5':'Record what actually happened and the value recovered.',
'proof.eyebrow':'Value after declaration','proof.title':'A resource becomes a traceable story.','proof.lead':'ECO-LOOP keeps the thread: origin, condition, match, action and result. The goal is to build trust without claiming absolute truth.','proof.t1':'Resource declared','proof.t2':'Context qualified','proof.t3':'Need identified','proof.t4':'Action completed','proof.t5':'Result tracked',
'cases.eyebrow':'Same logic, many situations','cases.title':'Not only waste. Resources, needs and possibilities.','cases.c1':'An office closes','cases.p1':'Furniture and equipment are identified, qualified and offered to actors who can reuse them.','cases.c2':'A construction site finishes','cases.p2':'Still-usable materials are identified before storage or disposal.','cases.c3':'A flow becomes available','cases.p3':'A by-product or dormant stock can be connected to another productive use.','cases.c4':'An item is no longer used','cases.p4':'ECO-LOOP first looks for another use, a repair or a transfer.',
'ai.eyebrow':'Intelligence','ai.title':'The more loops exist, the more the system learns.','ai.lead':'Matching can start with simple rules. Data from real loops can later improve matches and recommendations.',
'vision.eyebrow':'Mbôra vision','vision.title':'Keep value moving before it is lost.','vision.p':'Start with simple, measurable cases in Yaoundé, learn from real use, then gradually expand the loops and actors.','cta.title':'Before throwing away, replacing or buying: let’s see what already exists.','cta.demo':'Explore the demo','cta.contact':'Talk to Mbôra on WhatsApp','footer':'Concept prototype · Yaoundé, Cameroon',
'demo.loopBadge':'LOOP','demo.badge':'Interactive prototype','demo.back':'← Site','demo.eyebrow':'A resource · a context · a loop','demo.title':'What can still be done with this resource?','demo.lead':'Follow a fictional scenario: a company releases 80 chairs in good condition in Yaoundé. ECO-LOOP observes, qualifies, connects, triggers an action and follows the result.','demo.backbtn':'← Back','demo.start':'Start →','demo.next':'Continue →','demo.restart':'Replay the loop','demo.observe':'Observe','demo.context':'Qualify','demo.match':'Connect','demo.action':'Act','demo.follow':'Follow','demo.h1':'A resource appears. ECO-LOOP starts by observing it.','demo.h2':'Context turns an announcement into useful information.','demo.h3':'A compatible need appears. The loop can begin.','demo.h4':'A concrete action puts the resource back into circulation.','demo.h5':'The result is tracked to see what actually changed.','demo.dataResource':'80 chairs','demo.dataState':'Good condition','demo.dataCity':'Yaoundé','demo.dataNeed':'Equipment for a school','demo.dataActor':'Les Cocotiers School','demo.dataAction':'Transfer to the school','demo.dataResult':'80 chairs put back into use','demo.matchScore':'92%','demo.signal':'RESOURCE FLAGGED','demo.obsText':'80 chairs are available after an office closes. They are still usable.','demo.available':'Available','demo.resource':'Resource','demo.state':'Condition','demo.location':'Location','demo.possibilities':'Possibilities','demo.possibilitiesV':'Reuse · repair · transfer','demo.qualification':'Qualification','demo.qualificationV':'Enough information to search for a relevant path.','demo.need':'Need','demo.matchReason':'Same area · compatible quantity · suitable condition.','demo.compatible':'Plausible match','demo.actionTag':'ACTION CONFIRMED','demo.actionText':'The chairs are transferred to the school instead of being stored or discarded.','demo.confirmed':'Route confirmed','demo.followTag':'RESULT TRACKED','demo.resultText':'The resource found a new use. The loop leaves a trace of what actually happened.','demo.units':'units','demo.newUse':'new use','demo.tracked':'tracked','contact.whatsapp':'Contact Mbôra on WhatsApp · +237 680 485 422'
}};
let lang=localStorage.getItem('ecoloop-lang')||'fr';
function t(k){return (I18N[lang]&&I18N[lang][k])||k}
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));const b=document.getElementById('langToggle');if(b)b.textContent=lang==='fr'?'English':'Français';localStorage.setItem('ecoloop-lang',lang);document.dispatchEvent(new CustomEvent('languagechange'))}
document.getElementById('langToggle')?.addEventListener('click',()=>{lang=lang==='fr'?'en':'fr';applyLanguage()});applyLanguage();